const Brick = require('./bricks');

 var Levels = [
   [
     'OOOOOOOOOOOO',
     'OOOOOOOOOOOO',
     'OOOOOOOOOOOO',
     'OOOOOOOOOOOO',
     'OOOOOOOOOOOO',
     'OOOOOOOOOOOO',
     'OOOOOOOOOOOO',
     'OOOOOOOOOO#U',
   ],
   [
   '############',
   '############',
   '############',
   'OOOOOOOOOOOO',
   '############',
   'OOOOOOOOOOOO',
   'OOOOOOOOOOOO',
   'OOOOOOOOOOOO',
 ],
   [
   '############',
   'OOOOOOOOOOOO',
   '#M#M#M#M#M#M',
   'OOOOOOOOOOOO',
   'M#M#M#M#M#M#',
   'OOOOOOOOOOOO',
   '############',
   'OOOOOOOOOOOO',
 ],
 [
   '###M####M###',
   '##M######M##',
   '#M########M#',
   'M##########M',
   '#M########M#',
   '##M######M##',
   '###M####M###',
   'OOOOOOOOOOOO',
],
[
   '############',
   '#####OO#####',
   '#####OO#####',
   'OOOOOOOOOOOO',
   'OOOOOOOOOOOO',
   '#####OO#####',
   '#####OO#####',
   '############'
],
[
   '############',
   'O##########O',
   'OO########OO',
   'OUO######OUO',
   'OOOO####OOOO',
   'OUOOO##OOOUO',
   'OOOOOOOOOOOO',
   'OOOUOOOOUOOO',
],
[
   'OOOOMOOMOOOO',
   'OOO######MOO',
   'OO#O#OO#OOOO',
   'OOO######OOO',
   'OOOO#OO#O#OO',
   'OOOO#OO#O#OO',
   'OOM######OOO',
   'OOOOMOOMOOOO'
],
[
   '#U##OOOO##U#',
   '####OOOO####',
   '#U##OOOO##U#',
   'OOOOOOOOOOOO',
   'OOOOOOOOOOOO',
   '#M##OOOO##M#',
   '####OOOO####',
   '#M##OOOO##M#'
],
[
   'OOO###OOO###',
   '###OOO###OOO',
   'OOO###OOO###',
   '###OOO###OOO',
   'OOO###OOO###',
   '###OOO###OOO',
   'OOO###OOO###',
   '###OOO###OOO',
],
[
   '####OOOOOOOO',
   '#####OOOOOOU',
   '######OOOOOO',
   '#######OOOOU',
   '########OOOO',
   '#########OOU',
   '##########OO',
   '#M#M#M#M#M##'
],
[
   'OOOOU##UOOOO',
   'OMOOO##OOOMO',
   'OOOOU##UOOOO',
   'OMOOO##OOOMO',
   'OOOOU##UOOOO',
   'OMOOO##OOOMO',
   'OOOOU##UOOOO',
   'OMOOO##OOOMO'
],


];

module.exports = Levels;
